### ISSUE TITLE
Export PDF error.

### ISSUE THREAD

**Issue by tao12345666333** [tao12345666333/backslide#1]
```
root@8b3e807dc64c:/src# node /usr/local/lib/node_modules/backslide/node_modules/decktape/decktape.js .tmp/pdf/presentation.html  test/a.pdf
Error: Failed to launch chrome!
/usr/local/lib/node_modules/backslide/node_modules/decktape/node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/backslide/node_modules/decktape/node_modules/puppeteer/lib/Launcher.js:299:14)
    at Interface.helper.addEventListener (/usr/local/lib/node_modules/backslide/node_modules/decktape/node_modules/puppeteer/lib/Launcher.js:288:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:368:8)
    at Socket.onend (readline.js:147:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)

```

**Comment by tao12345666333** [comment]
```
Step 3/6 : RUN npm install --unsafe-perm -g backslide
 ---> Running in 2c26c192e915
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=3.10.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.6.8 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
/usr/local/bin/bs -> /usr/local/lib/node_modules/backslide/bin/bs

> hummus@1.0.87 install /usr/local/lib/node_modules/backslide/node_modules/decktape/node_modules/hummus
> node-pre-gyp install --fallback-to-build

[hummus] Success: "/usr/local/lib/node_modules/backslide/node_modules/decktape/node_modules/hummus/binding/hummus.node" is installed via remote

> puppeteer@1.7.0 install /usr/local/lib/node_modules/backslide/node_modules/decktape/node_modules/puppeteer
> node install.js


Chromium downloaded to /usr/local/lib/node_modules/backslide/node_modules/decktape/node_modules/puppeteer/.local-chromium/linux-579032

> node-sass@4.9.3 install /usr/local/lib/node_modules/backslide/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/linux-x64-57_binding.node
Download complete
Binary saved to /usr/local/lib/node_modules/backslide/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /root/.npm/node-sass/4.9.3/linux-x64-57_binding.node

> node-sass@4.9.3 postinstall /usr/local/lib/node_modules/backslide/node_modules/node-sass
> node scripts/build.js

Binary found at /usr/local/lib/node_modules/backslide/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/backslide/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ backslide@2.3.1
added 603 packages in 33.484s
Removing intermediate container 2c26c192e915
 ---> 1b03b0ef39ee
```
